### ISSUE TITLE
error while compiling: unexpected token: <>

### ISSUE THREAD

**Issue by woodyjon** [keanemind/react-gaugejs#2]
Hello,

Thank you for this wrapper.
I am trying to use it exactly as you explain it on the readme, but I have the following error when I compile:

```
./node_modules/react-gaugejs/Gauge.js
SyntaxError: /home/app/node_modules/react-gaugejs/Gauge.js: Unexpected token (72:4)

  70 | 
  71 |   return (
> 72 |     <>
     |     ^
  73 |       <canvas ref={canvas} {...passThroughProps}></canvas>
  74 |       <span ref={span} style={{display: 'none'}}></span>
  75 |     </>

```

I guess this is something evident that I am missing, but maybe you could help.

Thank you very much,
Regards,

Jonathan

**Comment by keanemind** [comment]
Hi Jonathan, it looks like the tooling you're using doesn't support the [React fragment shorthand syntax](https://reactjs.org/docs/fragments.html#short-syntax). You can replace the `<>` and `</>` tags with `<React.Fragment>` and `</React.Fragment>` respectively. I've updated the readme to use the longer syntax to help others avoid the same problem.

**Comment by woodyjon** [comment]
OK, I see. Thanks a lot.

**Comment by sara-graves** [comment]
Hey, I've got the same issue, even after replacing it with `<React.Fragment>` and `</React.Fragment>`. I've even tried `<div>`s instead and it's still not compiling. I'm not sure why.

**Comment by keanemind** [comment]
@sara-graves Could I see the compilation error?

**Comment by lalote** [comment]
SyntaxError: /Users/sarutobi/PROYECTOS_SATELNET/satelnetv2/node_modules/react-gaugejs/Gauge.js: Unexpected token (79:4)

  77 | 
  78 |   return (
> 79 |     <>
     |     ^
  80 |       <canvas ref={canvas} {...passThroughProps}></canvas>
  81 |       <span ref={span} style={{display: 'none'}}></span>
  82 |     </>

**Comment by lalote** [comment]
same thing here :(, React.Fragment doesnt help

**Comment by keanemind** [comment]
@lalote what versions of Node, React, and Babel are you using? I will try to reproduce the error.

**Comment by miguelfeliciano** [comment]
Any update?
I'm running into the same issue.  This wrapper is exactly what was needed as I got stuck after writing a speedometer with ChartJS and need to specify the segment lengths.

Error:
./node_modules/react-gaugejs/Gauge.js
SyntaxError: /Users/.../node_modules/react-gaugejs/Gauge.js: Unexpected token (79:4)

Running:
- React v16.3
- NPM v6.14.2
- Node v12.16.1
- Typescript v3.9
- Babel-loader v8.0.6

My compiler yells at me about a missing type definition file, but I can add that myself to the project typings folder.
